name: Android CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Cambia esto según la versión de Java que uses

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Asegúrate de agregar tu token en los secretos del repositorio
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=tu_proyecto  # Cambia esto por tu projectKey en SonarCloud
            -Dsonar.organization=tu_organizacion  # Cambia esto por tu organización en SonarCloud
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
